# Generated by Django 3.2.23 on 2023-11-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
