# Generated by Django 4.2.7 on 2023-11-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_logo',
        ),
    ]
