# Generated by Django 4.2.7 on 2023-12-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_business_owner_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=models.TextField(blank=True, default='No bio yet', max_length=250, null=True),
        ),
    ]
